[package]
# Semantic Versionning is used: https://semver.org/
version = "1.0.0"

# The title and description fields are primarily for displaying extension info in UI
title = "Camera Movement Extension"
description="Provide different camera movement/randomization to use with Replicator for synthetic data generation."

# Path (relative to the root) or content of readme markdown file for UI.
readme  = "docs/README.md"

# URL of the extension source repository.
repository = ""

# One of categories for UI.
category = "Synthetic Data"

# Keywords for the extension
keywords = ["kit", "replicator", "camera movement"]


# Use omni.ui to build simple UI
[dependencies]
"omni.kit.uiapp" = {}

# Main python module this extension provides, it will be publicly available as "import bmw.techoffice.anthonyyaghi.camera_mvt".
[[python.module]]
name = "bmw.techoffice.anthonyyaghi.camera_mvt"
